language: cpp
branches:
  only:
    - master
notifications:
  recipients:
    - debugler@gmail.com
  email:
    on_success: change
    on_failure: always
compiler:
    - gcc
env:
  global:
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - "ARTIFACTS_S3_BUCKET=debugler"
    - secure: "Sje6LO0jCVC+hP/029z601HTH4C9srFydjC5grh0IOZmcjkL3c6ReDej4szu\nH2EUA2PaUFyrZM4tPf3DFYH3AOmjwT/BBUnV4dOlwNB964bHtmjhcdJFD0BY\nA1AFToOi2CP7P0vRrpfEsXTEguoKlM9NsYGyGFgG0j1Z1gMXLYw="
    - secure: "Uaej3fzMtOThUpL484V77AZbHeXWF3tkhN8tHnaDLOLH+4NSEfqrkWOMgqFx\ntkK6mJsqTaW96ezonNJHyx/5GsPG5B57DCffZ7sKrmiC1YqZ3FM7dayaAT3y\noFfMs2Op54d2g3NzqU1z4iAH4pnTdQorgp0Qm5KvTHmuthkHTPA="
    - "export DISPLAY=:99.0"
    #workaround for issue #9  (Lnx Mesa: NativeSurfaceGlx ctor fails) done for UT tests to pass on Mesa
    - "LIBGL_ALWAYS_INDIRECT=1"

before_script:
  - "gem install travis-artifacts"
  - "sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test"
  - "sudo apt-get update"
  - "sudo apt-get install g++-4.7 x11proto-gl-dev libelf-dev python-opengl"
  - "sudo mount -t tmpfs shm /dev/shm"
  - "sh -e /etc/init.d/xvfb start"

script: mkdir build && cd build && CXX=g++-4.7 CC=gcc-4.7 cmake ../src -DCPACK_PACKAGE_VERSION_PATCH=$TRAVIS_JOB_NUMBER && make package && sudo dpkg -i debugler-0.1.$TRAVIS_JOB_NUMBER-Linux.deb && ./tests/UT/ut

after_success: # and this only on success
after_script:
  - "travis-artifacts upload --path debugler-0.1.$TRAVIS_JOB_NUMBER-Linux.deb --target-path artifacts/"
