language: cpp
branches:
  only:
    - master
notifications:
  recipients:
    - debugler@gmail.com
  email:
    on_success: change
    on_failure: always
compiler:
    - gcc

script: mkdir build && cd build && cmake ../src && make